<?php

namespace ID\Correios\Calculos;

use ID\Correios\Servicos;
use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-04 at 21:35:49.
 */
class CalculoPrecoPrazoTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var CalculoPrecoPrazo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CalculoPrecoPrazo;
        $this->object
            ->setCodServico(Servicos::SERV_PAC)
            ->setValor(1)
            ->setPrazoEntrega(1)
            ->setValorMaoPropria(1)
            ->setValorAvisoRecebimento(1)
            ->setValorDeclarado(0)
            ->setEntregaDomiciliar(true)
            ->setEntregaSabado(false);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setCodServico
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setValor
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setPrazoEntrega
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setValorMaoPropria
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setValorAvisoRecebimento
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setValorDeclarado
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setEntregaDomiciliar
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::setEntregaSabado
     */
    public function testSetters()
    {

    }

    /**
     * @depends testSetters
     *
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getCodServico
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getValor
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getPrazoEntrega
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getValorMaoPropria
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getValorAvisoRecebimento
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getValorDeclarado
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getEntregaDomiciliar
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getEntregaSabado
     */
    public function testGetters()
    {
        $this->assertEquals(Servicos::SERV_PAC, $this->object->getCodServico());
        $this->assertEquals(1, $this->object->getValor());
        $this->assertEquals(1, $this->object->getPrazoEntrega());
        $this->assertEquals(1, $this->object->getValorMaoPropria());
        $this->assertEquals(1, $this->object->getValorAvisoRecebimento());
        $this->assertEquals(0, $this->object->getValorDeclarado());
        $this->assertEquals(true, $this->object->getEntregaDomiciliar());
        $this->assertEquals(false, $this->object->getEntregaSabado());
    }

    /**
     * @covers ID\Correios\Calculos\CalculoPrecoPrazo::getNomeServico
     */
    public function testGetNomeServico()
    {
        $this->assertEquals('PAC Varejo', $this->object->getNomeServico());
    }
}
