language: php
script: vendor/bin/phpunit Tests/

php:
    - 5.4

before_script:
    - "composer install --dev --verbose"
    
before_install:
    - php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update