<?php

namespace ID\Correios\String;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-03 at 22:39:03.
 */
class StringTest extends \PHPUnit_Framework_TestCase
{
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ID\Correios\String\String::stringToDouble
     */
    public function testStringToDouble()
    {
        $this->assertEquals(15.8, String::stringToDouble('15,80'));
    }

    /**
     * @covers ID\Correios\String\String::validarCep
     *
     * @expectedException \InvalidArgumentException
     */
    public function testValidarCep()
    {
        String::validarCep('06870-120');
    }

    /**
     * @covers ID\Correios\String\String::validarCep
     */
    public function testValidarCepEhValido()
    {
        $this->assertTrue(String::validarCep('06870320'));
    }

}
