<?php

namespace ID\Correios;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-04 at 15:29:49.
 */
class CalculadoraFreteInterfaceTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var CalculadoraFrete
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testCalcular()
    {
        $this->getMock('\ID\Correios\CalculadoraFreteInterface');
    }
}