<?php

namespace ID\Correios;

use PHPUnit_Framework_TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-04 at 20:39:33.
 */
class ServicosTest extends PHPUnit_Framework_TestCase
{

    /**
     * @var Servicos
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Servicos;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers ID\Correios\Servicos::getNomeServico
     */
    public function testGetNomeServico()
    {
        $this->assertEquals('PAC Varejo', Servicos::getNomeServico(Servicos::SERV_PAC));
    }

    /**
     * @covers ID\Correios\Servicos::getNomeServico
     */
    public function testGetNomeServicoNaoExistente()
    {
        $this->assertEquals('', Servicos::getNomeServico(1234));
    }

    /**
     * @covers ID\Correios\Servicos::getServicos
     */
    public function testGetServicos()
    {
        $method = new \ReflectionMethod('ID\Correios\Servicos', 'getServicos');
        $method->setAccessible(true);

        $this->assertTrue(is_array($method->invoke($this->object)));
    }

}
